### ISSUE TITLE
Actividad 7. Infografía Hilos

### ISSUE THREAD

**Issue by santiagomary1004** [SistemasTecTlaxiaco/infografia-de-hilos-santiagomary1004#2]
Actividad 7. Infografía Hilos
Maribel Santiago Bautista 4BS
[Infografia_Hilos_MaribelSantiagoBautista.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-santiagomary1004/files/15045361/Infografia_Hilos_MaribelSantiagoBautista.pdf)

**Comment by Nancy-0714** [comment]
Si cumple con los criterios de la rubrica.
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
